name: Build

on:
  workflow_call:
    inputs:
      changed-files:
        required: true
        type: string
        description: Build relenv python builds

jobs:

  build_linux:

    strategy:
      fail-fast: false
      matrix:
        host:
          - x86_64
          - aarch64
        target:
          - x86_64
          - aarch64

    name: "Python Linux ${{ matrix.target }} on ${{ matrix.host }}"

    runs-on:
      - self-hosted
      - linux
      - src-build
      - ${{ matrix.host }}

    env:
      RELENV_DATA: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3


      - name: Install Dependencies
        run: |
          echo "$RELENV_DATA"

      - name: Install Dependencies
        run: |
          sudo apt-get install -y build-essential bison python3-all patchelf
          python3 -m pip install nox

      - name: Fetch Toolchain
        run: |
          python3 -m relenv toolchain fetch --arch=${{ matrix.target }}

      - name: Fetch Native Build
        if: ${{ matrix.host != matrix.target }}
        run: |
          python3 -m relenv fetch --arch=${{ matrix.target }}

      - name: Build
        run: |
          python3 -m relenv build --arch=${{ matrix.target }}

      - name: Verify Build
        if: ${{ matrix.host == matrix.target }}
        run: |
          python3 -m nox -e tests -- tests/test_verify_build.py

      - name: Linux Logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.host }}-${{ matrix.target }}-linux-gnu-logs
          path: logs/*
          retention-days: 5

      - name: "Upload artifact: build/${{ matrix.target }}-linux-gnu.tar.xz"
        uses: actions/upload-artifact@v3
        if: ${{ matrix.host == matrix.target }}
        with:
          name: ${{ matrix.target }}-linux-gnu.tar.xz
          path: build/${{ matrix.target }}-linux-gnu.tar.xz
          retention-days: 5

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-linux-${{ matrix.host }}-${{ matrix.target }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error

  build_macos:
    name: "Python macOS"

    #runs-on: macos-12
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64

    env:
      RELENV_DATA: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Install nox
        run: |
          pip3 install nox

      - name: Build
        run: |
          python3 -m relenv build

      - name: Verify Build
        run: |
          python3 -m nox -e tests -- tests/test_verify_build.py

      - name: MacOS Logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.arch }}-macos-logs
          path: logs/*
          retention-days: 5

      - name: Python build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}-macos.tar.xz
          path: build/${{ matrix.arch }}-macos.tar.xz
          retention-days: 5

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-macos-${{ matrix.arch }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error

  build_windows:
    name: "Python Windows"
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - x86

    env:
      RELENV_DATA: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Install VS Build Tools
        run: |
          relenv/_scripts/install_vc_build.ps1

      - name: Install nox
        run: |
          pip3 install nox

      - name: Fetch Native Build
        if: ${{ matrix.arch != 'amd64' }}
        run: |
          python3 -m relenv fetch

      - name: Build Python with Relenv
        run: |
          python -m relenv build --arch=${{ matrix.arch }}

      - name: Verify Build
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          nox -e tests -- tests/test_verify_build.py

      - name: Upload Build Logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.arch }}-windows-logs
          path: logs/*
          retention-days: 5

      - name: Upload Zipfile
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}-win.tar.xz
          path: build/${{ matrix.arch }}-win.tar.xz
          retention-days: 5

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-windows-${{ matrix.arch }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error
